FROM node:15.10.0

LABEL version="1.0"
LABEL description="This is the base docker image for the Sleep Management Group backend API"
LABEL maintainer = ["malokevi@gmail.com"]

WORKDIR /api

COPY ["./package.json", "./package-lock.json", "./"]
RUN ls
RUN npm install --production
COPY . .

EXPOSE 5000

CMD ["node", "app.js"]